name: core_elements
version: 0.0.1-pre.1
authors:
- Günter Zöchbauer <guenter@gzoechbauer.com>
description: >
  A Dart port of core-elements
  (http://polymer.github.io/core-docs/).
homepage: https://github.com/bwu-dart/core_elements
documentation: http://bwu-dart.github.io/core_elements/docs/index.html
environment:
  sdk: ">=1.4.0-dev.0 <2.0.0"
dependencies:
  polymer: ">=0.10.0-pre.10 <1.0.0"
#  polymer_ui_elements: #0.2.0-pre.7
#    git: https://github.com/ErikGrimes/polymer_ui_elements
#    path: ../polymer_ui_elements

dev_dependencies:
  unittest:  ">=0.10.1+2 <1.0.0"

transformers:
- polymer:
    entry_points:

